os:
  - linux
language: php
php:
  - "7.2"
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 8.10.0
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
before_install:
  - mysql -e 'CREATE DATABASE homestead_test;'
script:
  - npm run lint
  - npm run test
  - npm run production
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: ReLS/44uQ4k0LOZRtvGqB5W4FWM0D8j5R/vg/3SRzt6gPmmBt7qI+4JA+4bcP5eVxMoztWCslZ/O1aa9Am7l6Fb2BMnc7Xzw1/AO+5WcjYVKURjqVlvZVQXJcEyv9Pg4gAN510B/HLZ8xVUbLhXYgARQ5nDtNOvkBtJ67dItF7w121HZ9Ay5Tt6GX+w1Y5ZFC49ivTGld8sF892SlZmynFEGvtyYA2Vcu71kmzrL+VrEx6vGhZ8zX2vH02Rnmu9xWoosL5VtujzZLUskehJrBkz6Oc+DBZ2inzSuQWhWgxRCuJoUrkOqmJrbGuc2IQz2HT8UVe8IH0SMHS9RoKGZbEn5NNW2Rtr16Vi5ErQ2CO7yKSovdOTcSGFMF0f2JJAtfUTdKA1zbKFLWYj9aADAhW2gut2OzD5b0Yb5Q/TLbnd58u+8yG68su50hs2jkrNm2CC4U9Tf4eWUvuNYRsmVkqYFLqPSzGmIzW3q/59hFovRh1lu7E1H237R9yDAThaaC7Rz+b7MZ/EQP0K96vGDYM2MKd9oz0uj3SLw9/HlJrxlF3fmERg0Gy8oTkCH9RtletsWhrLPJMDzcGXEtwk9NSuOSELq0vHz5uLKJwc1LoK/mGFNHHiH6Vt6cPgvBOfUXktXvgGwT5oSl5iFP+LRTYogXLUqlMBBOHKsceqqKbU=
env:
  global:
    secure: u/doxuLyPIjitaOvqSFCjIEIGVMNKUyfe8eQaTFSU7QJ+76HqaQE/YlMzEe5UN7689XmX3LD0//KiYKIhN5QaTh8Bm/DVrPDX0e/rrlyn0P5C1gGUIGmy0K/qZEzXAXXVLvYOte+8uuj0tJkbYf6N99UgTJ0X6FUt19FfpeCRRez0zNcKwBBBN4EthLC/d3bT+aYlIad7Ye6Y8VYbUMJPwNkUc4a/cYV/8ssIWWIjUluY53wc0190RozgzsWsLMK6/22R6499ygaF+y5w5Rd8FxDaV7jXxH5ZNQOilm9v5BVC1nQ+iNIvjRF12AO+My14ZqlWvrasTlzGrhUa1TDnQ71at1dBoVk96/v9KyUj+elETpejobD3nqjUUvWWfFVYPvZDaefPY/FN4M5jIn/2iT2X9GS5/JdSpMDtUlu84MVTqDRMve2LWLw+COk+/H+ZBWpjLN5W6mbi5GoqmwuD7IdjaA95z4xLjEB4yAELB7NJqNf4GfIrnjzZmwc14OEZFm0tMS64zzzGl+XIwr1NrNlxjWmMiY5EW1UPNIUoOsUtIvYsHHcYLMVI6WsVdfnXjAkMgngPgZ2fMTWq2pMNEI2l8Zg+HNVIROKcynFFmLdrmhRqVRL1JkLSs63QBzPK5UcPycvKpa/jKyl7pXCjhepiKYJgjH5rXPZa8yolvA=
